<a href="https://colab.research.google.com/github/Major5846D/airbnb-eda/blob/main/PROJECT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import pandas as pd


In [98]:
listings = pd.read_csv('/content/listings.csv')
# reviews = pd.read_csv('/content/reviews.csv')
# neighbours = pd.read_csv('/content/neighbourhoods.csv')

In [99]:
df = listings.copy()

In [100]:
df.shape

(31069, 90)

In [101]:
df.head(1)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,979584324955463360,https://www.airbnb.com/rooms/979584324955463360,20260629030312,2026-07-02,city scrape,厨房可做饭免费Wi-Fi健身房泳池800米到坚果地铁站旅游打卡地,"Kick back and relax in this calm, stylish space.",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,262923052,...,4.95,4.73,4.55,NaN,NaN,44,44,0,0,0.68


In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31069 entries, 0 to 31068
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   id                                            31069 non-null  int64  
 1   listing_url                                   31069 non-null  object 
 2   scrape_id                                     31069 non-null  int64  
 3   last_scraped                                  31069 non-null  object 
 4   source                                        31069 non-null  object 
 5   name                                          31069 non-null  object 
 6   description                                   30490 non-null  object 
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   31069 non-null  object 
 9   host_id                                       31069 non-null 

In [103]:
df.index

RangeIndex(start=0, stop=31069, step=1)

In [104]:
df.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.106900e+04,3.106900e+04,0.0,3.106900e+04,3.106900e+04,0.0,31069.000000,31069.000000,31069.000000,31069.000000,...,20815.000000,20814.000000,20813.000000,0.0,0.0,31069.000000,31069.000000,31069.000000,31069.000000,20816.000000
mean,1.019842e+18,2.026063e+13,NaN,1.899194e+16,1.478389e+18,NaN,6.056970,5.368502,4.650713,5.335028,...,4.784868,4.668731,4.649647,NaN,NaN,32.449870,25.349866,6.643310,0.311275,1.005685
std,6.027655e+17,4.875078e+00,NaN,1.779345e+17,4.135058e+16,NaN,4.047831,3.414538,3.753182,3.368784,...,0.509846,0.473936,0.545395,NaN,NaN,49.412978,44.926178,23.407401,3.118309,2.028137
min,2.793400e+04,2.026063e+13,NaN,1.498300e+04,1.462507e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,7.198804e+17,2.026063e+13,NaN,6.934601e+07,1.463342e+18,NaN,2.000000,2.000000,1.000000,2.000000,...,4.800000,4.570000,4.590000,NaN,NaN,3.000000,1.000000,0.000000,0.000000,0.190000
50%,1.228113e+18,2.026063e+13,NaN,2.648650e+08,1.468251e+18,NaN,7.000000,5.000000,3.000000,5.000000,...,4.950000,4.790000,4.800000,NaN,NaN,10.000000,4.000000,0.000000,0.000000,0.510000
75%,1.521708e+18,2.026063e+13,NaN,5.486454e+08,1.470360e+18,NaN,10.000000,8.000000,8.000000,8.000000,...,5.000000,5.000000,5.000000,NaN,NaN,41.000000,29.000000,4.000000,0.000000,1.270000
max,1.717918e+18,2.026063e+13,NaN,1.718980e+18,1.718985e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,NaN,NaN,247.000000,238.000000,231.000000,62.000000,150.180000


In [105]:
 null = df.isnull().sum()
 null_columns  = null[null == df.shape[0]].index
 null_columns




Index(['neighborhood_overview', 'host_since', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_thumbnail_url',
       'host_neighbourhood', 'host_total_listings_count', 'host_verifications',
       'neighbourhood', 'neighbourhood_group_cleansed', 'calendar_updated',
       'license', 'instant_bookable'],
      dtype='object')

In [106]:
df = df.drop(columns = null_columns)

In [107]:
df.shape

(31069, 76)

## Step: Handling fully-empty columns
Dropped 14 columns that were 100% missing (e.g., host_about, license) —
these fields simply weren't captured in Bangkok's scrape. Not a data
quality issue, just missing by design in this dataset.

In [108]:
 null_summary =  df.isnull().sum()
 null_summary[null_summary > 0].sort_values(ascending = False)

,0
host_about,11988
review_scores_value,10256
review_scores_checkin,10255
review_scores_location,10255
review_scores_communication,10254
review_scores_accuracy,10253
last_review,10253
first_review,10253
review_scores_cleanliness,10253
review_scores_rating,10253


In [109]:
df[df['maximum_minimum_nights'].isnull()]['maximum_minimum_nights']


,maximum_minimum_nights
7948,NaN
28024,NaN


In [110]:
df.loc[[7948	, 28024]]


,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
7948,1617296148612092610,https://www.airbnb.com/rooms/1617296148612092610,20260629030312,2026-07-02,city scrape,Lumpiniville Sukhumvit,Long-term stay booking promotions are availabl...,https://a0.muscache.com/pictures/hosting/Hosti...,443225687,https://www.airbnb.com/users/show/443225687,...,4.56,4.56,4.78,4.67,4.78,1,0,1,0,1.91
28024,1168646596769294566,https://www.airbnb.com/rooms/1168646596769294566,20260629030312,2026-07-02,city scrape,c Super Luxury Villa-like Condo 10mins Ekkamai,A super luxurious and stylish villa-like condo...,https://a0.muscache.com/pictures/9f630b53-6e09...,234983307,https://www.airbnb.com/users/show/234983307,...,5.00,5.00,5.00,4.85,4.77,19,19,0,0,0.58


In [111]:
df.loc[[7948	, 28024]].isnull().sum().sort_values(ascending = False).head(10)


,0
maximum_minimum_nights,2
minimum_minimum_nights,2
maximum_nights,2
minimum_nights,2
maximum_maximum_nights,2
minimum_maximum_nights,2
host_about,1
host_location,1
id,0
listing_url,0


In [112]:
# df['maximum_minimum_nights'].median()
# df['minimum_minimum_nights'].median()
# df['minimum_maximum_nights'].median()
# df['maximum_maximum_nights'].median()




In [113]:
df['maximum_minimum_nights'].median()
df['minimum_minimum_nights'].median()
df['maximum_maximum_nights'].median()
df['minimum_maximum_nights'].median()
df['maximum_nights'].median()
df['minimum_nights'].median()



2.0

In [114]:
df['maximum_minimum_nights'].mean()
df['minimum_minimum_nights'].mean()
df['maximum_maximum_nights'].mean()
df['minimum_maximum_nights'].mean()
df['maximum_nights'].mean()
df['minimum_nights'].mean()


np.float64(12.783274857565907)

In [115]:
cols_to_fill = ['maximum_minimum_nights' , 'minimum_minimum_nights' , 'maximum_maximum_nights' , 'minimum_maximum_nights' , 'maximum_nights' , 'minimum_nights' ]


In [116]:
for col in cols_to_fill :
  df[col] = df[col].fillna(df[col].median())


In [117]:
df[cols_to_fill].isnull().sum()

,0
maximum_minimum_nights,0
minimum_minimum_nights,0
maximum_maximum_nights,0
minimum_maximum_nights,0
maximum_nights,0
minimum_nights,0


In [118]:
 null_summary =  df.isnull().sum()
 null_summary[null_summary > 0].sort_values(ascending = False)

,0
host_about,11988
review_scores_value,10256
review_scores_checkin,10255
review_scores_location,10255
review_scores_communication,10254
first_review,10253
review_scores_cleanliness,10253
review_scores_accuracy,10253
last_review,10253
review_scores_rating,10253


In [119]:
df[df['host_profile_url'].isnull()].isnull().sum()

,0
id,0
listing_url,0
scrape_id,0
last_scraped,0
source,0
...,...
calculated_host_listings_count,0
calculated_host_listings_count_entire_homes,0
calculated_host_listings_count_private_rooms,0
calculated_host_listings_count_shared_rooms,0


In [120]:
df['host_profile_url']

,host_profile_url
0,https://www.airbnb.com/users/profile/146939044...
1,https://www.airbnb.com/users/profile/146920674...
2,https://www.airbnb.com/users/profile/146959592...
3,https://www.airbnb.com/users/profile/146530973...
4,https://www.airbnb.com/users/profile/147072381...
...,...
31064,https://www.airbnb.com/users/profile/152953686...
31065,https://www.airbnb.com/users/profile/151083228...
31066,https://www.airbnb.com/users/profile/147040601...
31067,https://www.airbnb.com/users/profile/151083228...


## Step: Near-complete columns (nights group + host_profile_url)

7 columns had only 2 missing rows (7948, 28024) — verified these are real,
active listings, not broken data. Found strong right-skew in the numeric
columns (e.g., max_nights: median=365, mean=553,596), so imputed using median
instead of mean. host_profile_url left as NaN — not relevant to pricing analysis.

In [121]:
df.head(1)

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,979584324955463360,https://www.airbnb.com/rooms/979584324955463360,20260629030312,2026-07-02,city scrape,厨房可做饭免费Wi-Fi健身房泳池800米到坚果地铁站旅游打卡地,"Kick back and relax in this calm, stylish space.",https://a0.muscache.com/pictures/hosting/Hosti...,262923052,https://www.airbnb.com/users/show/262923052,...,4.45,4.86,4.95,4.73,4.55,44,44,0,0,0.68


In [139]:
 null_summary =  df.isnull().sum()
 null_summary[null_summary > 0].sort_values(ascending = False)

(25,)

In [127]:
[col for col in df.columns if 'review' in col.lower()]

['number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'number_of_reviews_ly',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'reviews_per_month']

In [129]:
df[df['number_of_reviews'] == 0].shape

(10253, 76)

In [142]:
df['has_reviews'] = df['number_of_reviews'] > 0
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)


In [135]:
df['reviews_per_month'].isnull().sum()

np.int64(0)

In [140]:
df.head(1)

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,has_reviews
0,979584324955463360,https://www.airbnb.com/rooms/979584324955463360,20260629030312,2026-07-02,city scrape,厨房可做饭免费Wi-Fi健身房泳池800米到坚果地铁站旅游打卡地,"Kick back and relax in this calm, stylish space.",https://a0.muscache.com/pictures/hosting/Hosti...,262923052,https://www.airbnb.com/users/show/262923052,...,4.86,4.95,4.73,4.55,44,44,0,0,0.68,True


In [146]:
 null_summary =  df.isnull().sum()
 null_summary[null_summary > 0].sort_values(ascending = False)

,0
host_about,11988
review_scores_value,10256
review_scores_checkin,10255
review_scores_location,10255
review_scores_communication,10254
review_scores_cleanliness,10253
review_scores_accuracy,10253
review_scores_rating,10253
first_review,10253
last_review,10253


In [145]:
df[['bathrooms', 'bedrooms', 'beds']].describe()

,bathrooms,bedrooms,beds
count,26947.000000,27172.000000,28418.000000
mean,1.381156,1.455101,1.830952
std,1.117763,1.287158,2.027435
min,0.500000,0.000000,1.000000
25%,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000
75%,1.000000,2.000000,2.000000
max,50.000000,50.000000,60.000000


In [149]:
df['room_type'].head()

,room_type
0,Entire home/apt
1,Private room
2,Entire home/apt
3,Private room
4,Entire home/apt


In [150]:
df.groupby('room_type')[['bathrooms' , 'bedrooms' , 'beds']].median()

,bathrooms,bedrooms,beds
room_type,,,
Entire home/apt,1.0,1.0,1.0
Hotel room,1.0,1.0,1.0
Private room,1.0,1.0,1.0
Shared room,1.0,1.0,2.0


In [156]:
for col in ['bathrooms' , 'bedrooms' , 'beds'] :
  df[col] = df.groupby('room_type')[col].fillna(df.groupby('room_type')[col].median())



/tmp/ipykernel_2077/4168634167.py:2: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df[col] = df.groupby('room_type')[col].fillna(df.groupby('room_type')[col].median())
/tmp/ipykernel_2077/4168634167.py:2: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df[col] = df.groupby('room_type')[col].fillna(df.groupby('room_type')[col].median())
/tmp/ipykernel_2077/4168634167.py:2: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df[col] = df.groupby('r

In [161]:
df.isnull().sum()[df.isnull().sum() > 0].sort_values(ascending = False)

,0
host_about,11988
review_scores_value,10256
review_scores_checkin,10255
review_scores_location,10255
review_scores_communication,10254
first_review,10253
last_review,10253
review_scores_rating,10253
review_scores_accuracy,10253
review_scores_cleanliness,10253


In [162]:
df['bathrooms_text']

,bathrooms_text
0,Half-bath
1,8 shared baths
2,1.5 baths
3,1 bath
4,1.5 baths
...,...
31064,1 bath
31065,1 bath
31066,1 private bath
31067,1 bath


## Step: bathrooms, bedrooms, beds

Checked median by room_type before deciding fill strategy. Found medians
were nearly identical across room types in this dataset, but chose to
impute using room_type-grouped median anyway (rather than flat overall
median) since it's conceptually more accurate and costs nothing extra.
Used median over mean due to right-skew from outliers (e.g., 50 bathrooms).